
default: run # specify the default Makefile target

.PHONY: build run clean

build:
	@echo "Building the project"

run: build
	@echo "Simulating the DUT"

clean:
	@echo "clean all build files"
	@-rm -rf build
